In [1]:
import pandas as pd
from utils import adjustDataframe, save_bigquery

#### Vagas

In [2]:
tabela = pd.read_json('../data/vagas.json')

In [3]:
tabela_trat = adjustDataframe(tabela, 'job_id')

In [4]:
tabela_trat.head()

,job_id,informacoes_basicas_data_requicisao,informacoes_basicas_limite_esperado_para_contratacao,informacoes_basicas_titulo_vaga,informacoes_basicas_vaga_sap,informacoes_basicas_cliente,informacoes_basicas_solicitante_cliente,informacoes_basicas_empresa_divisao,informacoes_basicas_requisitante,informacoes_basicas_analista_responsavel,...,perfil_vaga_areas_atuacao,perfil_vaga_principais_atividades,perfil_vaga_competencia_tecnicas_e_comportamentais,perfil_vaga_demais_observacoes,perfil_vaga_viagens_requeridas,perfil_vaga_equipamentos_necessarios,perfil_vaga_habilidades_comportamentais_necessarias,beneficios_valor_venda,beneficios_valor_compra_1,beneficios_valor_compra_2
0,5185,04-05-2021,00-00-0000,operation lead -,não,"morris, moran and dodson",dra. catarina marques,decision são paulo,maria laura nogueira,srta. bella ferreira,...,ti - sistemas e ferramentas-,operations lead\n\nroles & responsibilities:\n...,required skills:\n• prior experience in cloud ...,100% remoto período – entre 5 – 6 meses,,nenhum -,nan,-,r$,
1,5184,04-05-2021,00-00-0000,consultor pp/qm sênior,não,"morris, moran and dodson",dra. catarina marques,decision são paulo,maria laura nogueira,yasmin da rosa,...,ti - desenvolvimento/programação-,consultor pp/qm sr.\n\n• consultor pp/qm sênio...,• consultor pp/qm sênior com experiencia em pr...,• início: imediato • fim: jan/22,,nenhum -,nan,-,r$,
2,5183,04-05-2021,00-00-0000,analista pl/jr c/ sql,não,"morris, moran and dodson",dra. catarina marques,decision são paulo,maria laura nogueira,ana albuquerque,...,ti - sistemas e ferramentas-,descrição – atividades:\n\no monitoramento das...,requisitos mandatórios:\n\no conhecimentos téc...,localização: remoto perfil: analista pleno ou ...,,nenhum -,nan,-,r$,
3,5182,04-05-2021,18-05-2021,technical architect - 11894809,não,nelson-page,dr. raul monteiro,decision são paulo,cecília freitas,clara rios,...,ti - projetos-,descrição/comentário: architecture frameworks ...,descrição/comentário: architecture frameworks ...,budgeted rate - indicate currency and type (ho...,não,notebook padrão -,nan,- p/ mês (168h),fechado,
4,5181,04-05-2021,00-00-0000,consultor sap authorization (bca) -pleno / sênior,não,mann and sons,cauê fogaça,decision são paulo,maria laura nogueira,srta. bella ferreira,...,ti - sap-,experiência como consultor sap authorization (...,experiência como consultor sap authorization (...,contratação clt full pela decision locação rem...,sim,nenhum -,nan,-,r$,

In [5]:
save_bigquery(tabela_trat, 'fiap-4.datathon.vagas')

✔ Data saved at table: fiap-4.datathon.vagas (partition: none)

#### Applicants

In [17]:
table = pd.read_json('../data/applicants.json')

In [18]:
table.head()

,31000,31001,31002,31003,31004,31005,31006,31007,31008,31009,...,5990,5991,5992,5993,5994,5995,5996,5997,5998,5999
infos_basicas,"{'telefone_recado': '', 'telefone': '(11) 9704...","{'telefone_recado': '', 'telefone': '(11) 9372...","{'telefone_recado': '', 'telefone': '(11) 9239...","{'telefone_recado': '', 'telefone': '(11) 9810...","{'telefone_recado': '', 'telefone': '(11) 9251...","{'telefone_recado': '', 'telefone': '(11) 9498...","{'telefone_recado': '', 'telefone': '(11) 9484...","{'telefone_recado': '', 'telefone': '(31) 9986...","{'telefone_recado': '', 'telefone': '(11) 9288...","{'telefone_recado': '', 'telefone': '(11) 9535...",...,"{'telefone_recado': '', 'telefone': '(11) 9524...","{'telefone_recado': '', 'telefone': '(11) 9236...","{'telefone_recado': '', 'telefone': '(11) 9135...","{'telefone_recado': '', 'telefone': '(34) 9716...","{'telefone_recado': '', 'telefone': '(48) 9236...","{'telefone_recado': '', 'telefone': '(11) 9262...","{'telefone_recado': '', 'telefone': '(41) 9300...","{'telefone_recado': '', 'telefone': '(11) 9783...","{'telefone_recado': '', 'telefone': '(61) 9680...","{'telefone_recado': '', 'telefone': '(15) 9563..."
informacoes_pessoais,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...,{'data_aceite': 'Cadastro anterior ao registro...
informacoes_profissionais,"{'titulo_profissional': '', 'area_atuacao': ''...",{'titulo_profissional': 'Analista Administrati...,{'titulo_profissional': 'Administrativo | Fina...,"{'titulo_profissional': 'Área administrativa',...","{'titulo_profissional': '', 'area_atuacao': ''...",{'titulo_profissional': 'Administrativa/logíst...,{'titulo_profissional': 'Analista Administrati...,{'titulo_profissional': 'Desejo fazer parte do...,"{'titulo_profissional': '', 'area_atuacao': ''...","{'titulo_profissional': '', 'area_atuacao': ''...",...,"{'titulo_profissional': 'Crm', 'area_atuacao':...","{'titulo_profissional': 'Crm', 'area_atuacao':...","{'titulo_profissional': 'Crm', 'area_atuacao':...","{'titulo_profissional': 'Crm', 'area_atuacao':...","{'titulo_profissional': 'Crm', 'area_atuacao':...",{'titulo_profissional': 'Crm / Líder de Projet...,"{'titulo_profissional': 'Crm', 'area_atuacao':...","{'titulo_profissional': 'Crm', 'area_atuacao':...","{'titulo_profissional': 'Crm', 'area_atuacao':...","{'titulo_profissional': 'Crm', 'area_atuacao':..."
formacao_e_idiomas,"{'nivel_academico': '', 'nivel_ingles': '', 'n...",{'nivel_academico': 'Ensino Superior Incomplet...,{'nivel_academico': 'Ensino Superior Completo'...,{'nivel_academico': 'Ensino Superior Incomplet...,"{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': 'Ensino Técnico Completo',...",{'nivel_academico': 'Ensino Superior Cursando'...,{'nivel_academico': 'Ensino Superior Completo'...,"{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': '', 'nivel_ingles': '', 'n...",...,"{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': '', 'nivel_ingles': '', 'n...","{'nivel_academico': '', 'nivel_ingles': '', 'n..."
cargo_atual,{},{},{},{},{},{},{},{},{},{},...,{},{},{},{},{},{},{},{},{},{}

In [19]:
table_trat = adjustDataframe(table, 'applicant_id')

In [20]:
table_trat.head()

,applicant_id,infos_basicas_telefone_recado,infos_basicas_telefone,infos_basicas_objetivo_profissional,infos_basicas_data_criacao,infos_basicas_inserido_por,infos_basicas_email,infos_basicas_local,infos_basicas_sabendo_de_nos_por,infos_basicas_data_atualizacao,...,cargo_atual_cargo_atual,cargo_atual_projeto_atual,cargo_atual_cliente,cargo_atual_unidade,cargo_atual_data_admissao,cargo_atual_data_ultima_promocao,cargo_atual_nome_superior_imediato,cargo_atual_email_superior_imediato,cv_pt_0,cv_en_0
0,31000,NaT,(11) 97048-2708,,10-11-2021 07:29:49,luna correia,carolina_aparecida@gmail.com,,,10-11-2021 07:29:49,...,nan,nan,nan,nan,nan,nan,nan,nan,assistente administrativo\n\n\nsantosbatista\n...,NaT
1,31001,NaT,(11) 93723-4396,analista administrativo,10-11-2021 08:56:16,laura pacheco,eduardo_rios@hotmail.com,"são paulo, são paulo",outros,11-11-2021 11:10:31,...,nan,nan,nan,nan,nan,nan,nan,nan,formação acadêmica\nensino médio (2º grau) em ...,NaT
2,31002,NaT,(11) 92399-9824,administrativo | financeiro,10-11-2021 09:01:00,laura pacheco,pedro_henrique_carvalho@gmail.com,"são paulo, são paulo",anúncio,10-11-2021 11:42:36,...,nan,nan,nan,nan,nan,nan,nan,nan,objetivo: área administrativa | financeira\n\n...,NaT
3,31003,NaT,(11) 98100-1727,área administrativa,10-11-2021 09:08:13,laura pacheco,thiago_barbosa@hotmail.com,"são paulo, são paulo",site de empregos,10-11-2021 16:04:51,...,nan,nan,nan,nan,nan,nan,nan,nan,formação\nensino médio completo\ninformática i...,NaT
4,31004,NaT,(11) 92517-2678,,10-11-2021 09:18:46,maria clara pires,diogo_das_neves@hotmail.com,,,10-11-2021 09:22:03,...,nan,nan,nan,nan,nan,nan,nan,nan,última atualização em 09/11/2021\n­ sp\n\nensi...,NaT

In [21]:
table_trat[table_trat['applicant_id'] == 22406]

Empty DataFrame
Columns: [applicant_id, infos_basicas_telefone_recado, infos_basicas_telefone, infos_basicas_objetivo_profissional, infos_basicas_data_criacao, infos_basicas_inserido_por, infos_basicas_email, infos_basicas_local, infos_basicas_sabendo_de_nos_por, infos_basicas_data_atualizacao, infos_basicas_codigo_profissional, infos_basicas_nome, informacoes_pessoais_data_aceite, informacoes_pessoais_nome, informacoes_pessoais_cpf, informacoes_pessoais_fonte_indicacao, informacoes_pessoais_email, informacoes_pessoais_email_secundario, informacoes_pessoais_data_nascimento, informacoes_pessoais_telefone_celular, informacoes_pessoais_telefone_recado, informacoes_pessoais_sexo, informacoes_pessoais_estado_civil, informacoes_pessoais_pcd, informacoes_pessoais_endereco, informacoes_pessoais_skype, informacoes_pessoais_url_linkedin, informacoes_pessoais_facebook, informacoes_pessoais_download_cv, informacoes_profissionais_titulo_profissional, informacoes_profissionais_area_atuacao, informacoes_profissionais_conhecimentos_tecnicos, informacoes_profissionais_certificacoes, informacoes_profissionais_outras_certificacoes, informacoes_profissionais_remuneracao, informacoes_profissionais_nivel_profissional, informacoes_profissionais_qualificacoes, informacoes_profissionais_experiencias, formacao_e_idiomas_nivel_academico, formacao_e_idiomas_nivel_ingles, formacao_e_idiomas_nivel_espanhol, formacao_e_idiomas_outro_idioma, formacao_e_idiomas_instituicao_ensino_superior, formacao_e_idiomas_cursos, formacao_e_idiomas_ano_conclusao, formacao_e_idiomas_outro_curso, cargo_atual_id_ibrati, cargo_atual_email_corporativo, cargo_atual_cargo_atual, cargo_atual_projeto_atual, cargo_atual_cliente, cargo_atual_unidade, cargo_atual_data_admissao, cargo_atual_data_ultima_promocao, cargo_atual_nome_superior_imediato, cargo_atual_email_superior_imediato, cv_pt_0, cv_en_0]
Index: []

[0 rows x 58 columns]

In [10]:
save_bigquery(table_trat, 'fiap-4.datathon.applicants')

✔ Data saved at table: fiap-4.datathon.applicants (partition: none)

#### Prospects

In [11]:
table = pd.read_json('../data/prospects.json')

In [12]:
table_trat = adjustDataframe(table, 'job_id', explode_df=True)

In [13]:
table_trat.job_id.value_counts()

job_id
2676     25
13264    25
2552     25
8221     25
12018    25
         ..
14104     1
14110     1
14139     1
14147     1
14148     1
Name: count, Length: 11279, dtype: Int64

In [14]:
table_trat[table_trat.job_id == 2676].head()

,job_id,titulo_0,modalidade_0,prospect_num,nome,codigo,situacao_candidado,data_candidatura,ultima_atualizacao,comentario,recrutador
10056,2676,data engineer - sr - re-232128_1,,0,leonardo dias,20869,não aprovado pelo cliente,14-08-2020,21-08-2020,cliente não aprovou o candidato,srta. bella ferreira
18706,2676,data engineer - sr - re-232128_1,,1,natália farias,20817,desistiu,11-08-2020,11-08-2020,cadastrado na vaga errada,eloah leão
25354,2676,data engineer - sr - re-232128_1,,2,dr. matheus porto,20811,em avaliação pelo rh,11-08-2020,11-08-2020,,eloah leão
30400,2676,data engineer - sr - re-232128_1,,3,allana albuquerque,20668,em avaliação pelo rh,31-07-2020,31-07-2020,,eloah leão
34324,2676,data engineer - sr - re-232128_1,,4,dra. ana luiza freitas,20667,em avaliação pelo rh,31-07-2020,31-07-2020,,eloah leão

In [15]:
table_trat.dtypes

job_id                 Int64
titulo_0              object
modalidade_0          object
prospect_num           Int64
nome                  object
codigo                 Int64
situacao_candidado    object
data_candidatura      object
ultima_atualizacao    object
comentario            object
recrutador            object
dtype: object

In [16]:
save_bigquery(table_trat, 'fiap-4.datathon.prospects')

✔ Data saved at table: fiap-4.datathon.prospects (partition: none)